#!/bin/bash
for args
do
	case $args in
	"http")
		printf "\n"
		curl -s "https://raw.githubusercontent.com/ItzRazvyy/ProxyList/main/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saisuiu/uiu/main/cnfree.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saisuiu/uiu/main/free.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/premium.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/fate0/proxylist/master/proxy.list" | python3 utils/parsefate0.py http
		printf "\n"
		curl -s "https://raw.githubusercontent.com/arunsakthivel96/proxyBEE/master/proxy.list" | python3 utils/parsebee.py http
		printf "\n"
		curl -s "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt"
		printf "\n"
		curl -s "https://github.com/mertguvencli/http-proxy-list/blob/main/proxy-list/data.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=100&format=txt&type=http"
		printf "\n"
		curl -s "https://proxyspace.pro/http.txt"
		printf "\n"
		curl -s "https://www.ipaddress.com/proxy-list/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "http://www.httptunnel.ge/ProxyListForFree.aspx" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://www.proxyscan.io/download?type=http"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=20&format=txt"
		printf "\n"
		curl -s "http://www.proxylists.net/http_highanon.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/rx443/proxy-list/main/online/http.txt"
		printf "\n"
		curl -s "https://api.proxyscrape.com/?request=getproxies&proxytype=http&country=all&ssl=all&anonymity=all"
		printf "\n"
		curl -s "https://free-proxy-list.net/anonymous-proxy.html" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://www.google-proxy.net/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt"
	;;
	"https")
		printf "\n"
		curl -s "http://www.httptunnel.ge/ProxyListForFree.aspx" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://www.ipaddress.com/proxy-list/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/ItzRazvyy/ProxyList/main/https.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/premium.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/fate0/proxylist/master/proxy.list" | python3 utils/parsefate0.py https
		printf "\n"
		curl -s "https://raw.githubusercontent.com/arunsakthivel96/proxyBEE/master/proxy.list" | python3 utils/parsebee.py https
		printf "\n"
		curl -s "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt"
		printf "\n"
		curl -s "https://github.com/mertguvencli/http-proxy-list/blob/main/proxy-list/data.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/RX4096/proxy-list/main/online/https.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=100&format=txt&type=https"
		printf "\n"
		curl -s "https://proxyspace.pro/https.txt"
		printf "\n"
		curl -s "http://api.foxtools.ru/v2/Proxy.txt"
		printf "\n"
		curl -s "https://www.proxyscan.io/download?type=http"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=20&format=txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/rx443/proxy-list/main/online/https.txt"		
		printf "\n"
		curl -s "https://api.proxyscrape.com/?request=getproxies&proxytype=https&country=all&ssl=all&anonymity=all"
		printf "\n"
		curl -s "https://www.google-proxy.net/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://www.sslproxies.org/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
	;;
	"socks4")
		printf "\n"
		curl -s "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/ItzRazvyy/ProxyList/main/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks4/socks4.txt"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=100&format=txt&type=socsk4"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saisuiu/uiu/main/free.txt"
		printf "\n"
		curl -s "https://www.proxyscan.io/download?type=socks4"
		printf "\n"
		curl -s "https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&country=all&ssl=all&anonymity=all"
		printf "\n"
		curl -s "https://spys.me/proxy.txt" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://www.socks-proxy.net/" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks4.txt"
	;;
	"socks5")
		printf "\n"
		curl -s "https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/ItzRazvyy/ProxyList/main/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/socks5/socks5.txt"
		printf "\n"
		curl -s "http://pubproxy.com/api/proxy?limit=100&format=txt&type=socsk5"
		printf "\n"
		curl -s "https://proxyspace.pro/socks5.txt"
		printf "\n"
		curl -s "https://www.proxyscan.io/download?type=socks5"
		printf "\n"
		curl -s "https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&country=all&ssl=all&anonymity=all"
		printf "\n"
		curl -s "https://spys.me/proxy.txt" | sed -e 's/<[^>]*>//g' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{2,4\}'
		printf "\n"
		curl -s "https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt"
		printf "\n"
		curl -s "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks5.txt"
	;;
	*)
	;;
	esac
done